- Casks/talosctl.rb
- README.md
> chore: update to 0.8.5

- Casks/talosctl.rb
- README.md
> chore: update to 0.9.0

- Casks/talosctl.rb
- README.md
Add a note to README.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@gmail.com>
> chore: update to 0.10.0

- Casks/talosctl.rb
Just bump version and checksum.
Signed-off-by: Serge Logvinov <serge.logvinov@sinextra.dev>
> chore: update to 0.12.1

- Casks/talosctl.rb
- README.md
And tweak README instructions.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@talos-systems.com>
> chore: update to v0.12.3

- Casks/talosctl.rb
> Upgrading talosctl to v0.13.4

- Casks/talosctl.rb
> Update to v0.14.1

- Casks/talosctl.rb
Signed-off-by: Thorsten Schifferdecker <schifferdecker@b1-systems.de>
> update to v1.0.3

- Casks/talosctl.rb
Signed-off-by: Thorsten Schifferdecker <schifferdecker@b1-systems.de>
> chore: update to v1.0.6

- Casks/talosctl.rb
> chore: update to v1.1.0

- Casks/talosctl.rb
Updating talosctl to v1.1.2 with brew cask checks
> Update to version 1.1.2

- Casks/talosctl.rb
Signed-off-by: Thorsten Schifferdecker <schifferdecker@b1-systems.de>
> chore: update to v1.2.0

- Casks/talosctl.rb
> Upgrade to 1.2.2

- Casks/talosctl.rb
Signed-off-by: Thorsten Schifferdecker <schifferdecker@b1-systems.de>
> chore: update to v1.2.4

- Casks/talosctl.rb
> chore: update to v1.2.6

- Formula/talosctl.rb
Upgrade the version of talosctl
> Upgrade version of talosctl

- update.sh
Usage:
```bash
./update.sh 1.4.7
```
Requirements:
- bash
- sed
- wget
> feat: add update.sh script

- Formula/talosctl.rb
- update.sh
Also sneakily included a small fix for `update.sh`.
> chore: update to 1.5.4

- README.md
Renamed the repo to conform to community patterns and make it more general purpose.
> Update new repo name

- Formula/talosctl.rb
Formulas support adding in command completion with https://rubydoc.brew.sh/Formula.html#generate_completions_from_executable-instance_method
> feat: add support for command completion

- Formula/omnictl.rb
- README.md
- update.sh
I've never written a homebrew formula so I just copied the talosctl formula and updated it to make omnictl available. I also updated the readme.
Resolves #58
> feat: add omnictl

- Formula/sidero-tools.rb
- README.md
Meta package to install required tools and keep them up to date
> feat: add sidero labs tools formula

- Formula/omnictl.rb
- Formula/talosctl.rb
Update both formula to latest releases.
> update: talosctl and omnictl releases
